include(ExternalProject)

if (${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
    set(MACOSX TRUE)
endif()

function(prepare_dependency)
    set(optionArgs "")
    set(oneValueArgs NAME)
    set(multiValueArgs TARGETS)
    cmake_parse_arguments(FUNCTION_ARGS "${optionArgs}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    foreach(target IN LISTS FUNCTION_ARGS_TARGETS)
        if (TARGET ${target})
            get_target_property(target_type ${target} TYPE)
            if (target_type STREQUAL "EXECUTABLE" OR target_type STREQUAL "STATIC_LIBRARY" OR target_type STREQUAL "MODULE_LIBRARY" OR target_type STREQUAL "SHARED_LIBRARY")
                if (MSVC)
                    target_compile_options(${target} PRIVATE /W0)
                else()
                    target_compile_options(${target} PRIVATE -w)
                endif()
            endif()
            set_property(TARGET ${target} PROPERTY FOLDER ${FUNCTION_ARGS_NAME})
        endif()
    endforeach()
endfunction()

include(LinkToWasabi)
include(loguru)
